#!/usr/bin/perl -CLDSA

use strict;
use utf8;
use BE::GenRE;
use File::Glob ':bsd_glob';
#binmode STDIN, ":encoding(UTF-8)";
#binmode STDOUT, ":encoding(UTF-8)";

my $srt_re = qr/\.(srt|vtt|ttml)$/;

my $delete_these_prefixes = <<EOF;
3sat
3sat Filmkultur
3sat Wissenschaftsdoku
Aktuelles Und Gesellschaft
Alpha-doku
ARD Wissen
ARTE Concert - Pop
BR
Comedy & Satire
Comedy & Satire im Ersten
Das Erste
Der Fernsehfilm Der Woche
DokFilm
DokThema
Doku
Doku @ ONE
Doku & Reportage
Doku In Einsfestival
Doku Natur
Doku Plus
Doku Tiere
Doku-Reihe
Doku-Serie
Dokumentarfilm
Dokumentarfilme
Dokumentation
Dokumentation Und Reportage
Dokumentationen
Dokumentationen Und Reportagen
Dokus & Reportagen
Dokus Im Ersten
Dokus Und Reportagen
Einzelbeitrag SWR Fernsehen
Entdeckung
Entdeckung Der Welt - Leben Anderswo
Entdeckung Der Welt - Natur Und Tiere
Entdeckung Der Welt - Reisen
Erstaustrahlungen Bei ZDFinfo
Erstausstrahlungen Bei ZDFinfo
Fernsehfilm
Fernsehfilme
Fernsehfilme Und Serien
Fernsehserie
Film
Film & Serie
Film & Serie In Einsfestival
Film Ab!
Film Im NDR
Film Im Rbb
Film Und Serie
Filme
Filme & Serien Am Nachmittag
Filme, Dokus, Kabarett
Filme Im Ersten
Filme Im MDR
Filmgrößen
Ganze Filme Im ZDF
Geschichte - Biographien
Geschichte - Die Zeit Vor Dem 20. Jahrhundert
Geschichte - Das 20. Jahrhundert
Geschichte & Entdeckungen
Geschichtsdokumentationen
Hintergrund
Jugend
Kabarett
Kinder & Jugend
Kinderfilme Und Kinderdokus
Kino
Kinozeit
Kissenkino
Kissenkino Im MDR
Krimi Und Thriller
Krimis Im Ersten
Kultur & Religion
Kultur Und Pop - Kunst
Kultur Und Pop - Popkultur
Magazin
MDR Dok
MDR+
Musik und Theater
Natur
Naturfilme
NDR Dokfilm
Politik & Gesellschaft
Politik Und Gesellschaft
Rbb Fernsehen
Reportage & Dokumentation
Reportagen Und Recherchen
Serien
Séries et fictions - Séries
Spielfilm
Spielfilm-Highlights
Terra X
Tiere
Unterhaltung
WDR
WDR.DOK
Wissenschaft - Gesundheit Und Medizin
Wissenschaft - Technik Und Innovation
Wissenschaft - Umwelt Und Natur
Wissenschaft - Wissen Kompakt
Wissenschaftsdoku
ZDF-History
ZDFinfo
ZDFinfo Doku
ZDFneo
ZDFzeit
EOF

my $prefix_re = ListToRE(split(/\n/, $delete_these_prefixes));
#die "$prefix_re";

my $noop=0;
for my $f (@ARGV) {
	if ($f eq '-n') {
		$noop = 1;
		next;
	}
	my $F = $f;
	my $recode=0; # srt
	$F =~ s/\xa0/ /g;
	while ($F =~ s/^$prefix_re - //i) {};

	# things like "42 – Die Antwort Auf Fast Alles-Können Wir Auf Dem Mond Leben?-1344733279 - 1080p.mp4"
	if($F =~ s/-\d{10}(\.[^.]+)$/$1/) { / - / || s/-/ - /};

	#fix xtensions
	$F =~ s/\.mp4\.(ttml|txt|html|xml)$/.$1/;
	($F =~ s/\.mp4\.(?:tt|ht|x)ml.srt$/.srt/) && ($recode=1);

	$F =~ / - / || $F =~ s/\b: / - /;
	$F =~ s/^./\u$&/; $F =~ s/\s\S/\U$&/g; $F =~s/\bOf\b/of/g;
	$F =~ s/^(([^-:]+?): ([^-:]+?)) - \1/$2 - $3/;
	$F =~ s/^(.*?) - \1: /$1 - /;

	$F =~ s/^(.*?) - Faszination Erde Mit Dirk Steffens\b/Faszination Erde - $1/;
	$F =~ s/^Abenteuer Wildnis - (.*?) · ([^-.]+)/$1 - $2/;

	$F =~ s/ - ([^-]*)\s*\((?:Folge )?(\d+)__(\d+)(?:,\s*([^)]+))?\)/my $l=length($2);sprintf(" - %$l.${l}d of %d %s %s", $2, $3, $1, $4?" - ".$4:"")/e
	|| $F =~ s/\s*\((?:Folge )?(\d+)__(\d+)(?:,\s*([^)]+))?\)( - )/my $l=length($2);sprintf("%s%$l.${l}d of %d %s", $4||" ", $1, $2, $3?"($3)":"")/e;
	$F =~ s/\s+/ /g;
	$F =~ s/ \././g;
	if ($F =~ $srt_re) {
		my $FwS = $F; $FwS =~ s/$srt_re/ - *.m??/;
		$recode=1;
	}
	if ($F ne $f) {
		print("$f -> $F\n");
		system {"/bin/mv"} ("mv", "-i", $f, $F) unless $noop;
	};
	#if ($recode) {system {"/usr/bin/recode"} ("recode", "utf8..latin1", $F);}
	if ($F =~ /\.(mp4|mkv)/i) {system {"/usr/bin/env"} ("env", "vheight", "-r", $F);}
}
 