#!/bin/sh
for f in "$@"
do
	mkvpropedit "$f" -e track:a1 -s name="Deutsch" -s language=ger -e track:a2 -s name="English" -s language=eng
	mkvpropedit "$f" -e track:s1 -s name="Deutsch" &&\
	mkvpropedit "$f" -e track:s2 -s name="English"
	pmv 's/\s\d+p\W/ de,en$&/||s/\./ - de,en./' "$f" -ev
done
