#!/usr/bin/perl
use warnings;
use strict;
use BE::Dir;
use BE::Filter;
use BE::GenRE;
use Getopt::Long qw(:config bundling);

use BE::mov::Languages qw(%Languages);
use BE::mov::Filename;

my $noop = 0;
my $keepfiles = 0;
my $one_lang = 0;

sub help()
{
	print <<EOF;
$0 [options] file_prefix [file_prefix] ...

file_prefix: Name of the file to be merged
             (an extension is automatically removed)

Options:
  -h --help       This text
  -k --keepfiles  Don't delete the source files even on success
  -n --noop       Don't execute the merge commands, just print them
  -A --lang-audio Set the language for the audio tracks
  -S --lang-st    Set the language for the subtitle tracks
                  (Both are used as needed, be careful)
  -O --one_lang  Use the same language for all files

Examples:
  $0 movie_name.m4a -k
  $0 --noop movie_name

EOF
}

my @lang_audio;
my @lang_st;

GetOptions(
	"h|help"         => \&help,
	"n|noop"         => \$noop,
	"k|keepfiles"    => \$keepfiles,
	"A|lang-audio=s" => \@lang_audio,
	"S|lang-st=s"    => \@lang_st,
	"O|one_lang"     => \$one_lang,
);

sub deleteFromArray_eq(\@$) {
	my ($a, $needle);
	for (my $i=0; $i < @$a; $i++) {
		if ($a->[$i] eq $needle) {
			splice(@$a, $i, 1);
			last;
}	}	}

sub add_prefix_n($@) {
	my $prefix = shift;
	return "".join("", map {"$prefix$_\n"} @_);
}

my $newline = ""; # not print newline before first file
for my $f (@ARGV) {
	print $newline;
	$newline = "\n"; # actually print nnewline on second to last file
	my ($fb, $fe) = ($f =~ /(.*)\.([^.]+)/);
	if (!defined $fe) {
		$fb = $f;
		$fe = undef;
	}

	my $dirname = dirname($f);
	my $direntries = get_direntries($dirname);
	$f =~ s,^.*/,,;

	my (@fv, @fa, @fs, @fu, @fc, %unlink, %notunlink);
	my ($rev, $rea, $res, $reu, $rec) = (
		ListToRE(qw(m4v webmv mp4v ts)),
		ListToRE(qw(m4a aac webma opus webm)),
		qr,\Q$fb\E(.*)\.(?:srt|vtt)$,, # Subtitles
		ListToRE(qw(mp4 webm)),
		qr,\Q$fb\E(.*)\.chapters$,, # Subtitles
	);
	$rev = qr,^\Q$fb\E(.*)\.$rev$,; # Video
	$rea = qr,^\Q$fb\E(.*)\.$rea$,; # Audio
	$reu = qr,^\Q$fb\E(.*)\.$reu$,; # Unknown

	list_filter_re_arr(@$direntries,
		$rev => \@fv,
		$rea => \@fa,
		$res => \@fs,
		$reu => \@fu,
		$rec => \@fc);
	for my $fu (@fu) {
		my $fn = BE::mov::Filename->new($fu->[0]);
		$fn->probe();
		die unless $fn->{json};
#		print Data::Dumper->Dump([$fn->{json}], ["fn->{json}"]);
		my $have_v = 0;
		my $have_a = 0;
		for my $stream (@{$fn->{json}{streams}}) {
			my $codec_type = $stream->{codec_type};
			if ($codec_type eq 'video') {
				$have_v = 1;
				last if $have_a;
			} elsif ($codec_type eq 'audio') {
				$have_a = 1;
				last if $have_v;
			} else {die};
		}
		if ($have_v) {
			if ($have_a) {
				print "Complete video (won't use): $fu->[0]\n";
			} else {
				push(@fv, $fu);
			}
		} elsif ($have_a) {
			push(@fa, $fu);
		} else {
			print "No video / audio stream: fu->[0]\n";
		}
	}

	if (!@fv) {
		print STDERR "did not find adequate video stream file for $f in $dirname\n";
		next;
	}
	print add_prefix_n("Video: ", map {$_->[0]} @fv);
	if (!@fa) {
		print STDERR "did not find adequate audio stream file for $f in $dirname\n";
		next;
	}
	print add_prefix_n("Audio: ", map {$_->[0]} @fa);
	print add_prefix_n("Subtitle: ", map {$_->[0]} @fs);
	print add_prefix_n("Chapters: ", map {$_->[0]} @fc);

	for my $fv (@fv) {
		my $fn = BE::mov::Filename->new($fb . ($fv->[1] ne ""? "$fv->[1]" : "").".mkv");
		$fn->{lang} = [];
		$fn->{st} = [];
		$fn->{ext} = "mkv";
		my $fffileidx=0;
		my @cmd_fv = ("avconv", "-hide_banner", "-i", $fv->[0]);
		my @cmd_fa = ();
		my @cmd_fs = ();
		my @cmd_fc = ();
		my @cmd_maps = ('-map', $fffileidx++);
		my @cmd_meta = ();
		my @la = ();
		my @ls = ();
		my @files = ($fv->[0]);
		my $s = "";
		my $ffaudioidx = 0;
		for my $fa (sort {$a->[0] cmp $b->[0]} @fa) {
			my $extra = $fa->[1];
			$extra =~ s/^\s+//;
			$extra =~ s/\s+$//;
			$extra =~ s/^- //;
			my $s = $extra;
			if (@lang_audio) {
				$s = $lang_audio[0];
				shift @lang_audio if !$one_lang;
			};
			if ($s =~ /^[a-z]{2}$/) {
				push(@{$fn->{lang}}, $s);
				push(@la, $s);
				if (defined $Languages{$s}) {
					push(@cmd_meta, "-metadata:s:a:$ffaudioidx",
						 "title=$Languages{$s}{name}",
						"-metadata:s:a:$ffaudioidx",
						 "language=$Languages{$s}{code3}");
				} else {
					goto default_lang;
				}
			} elsif ($s =~ /^[a-z]{3}$/) {
				push(@cmd_meta, "-metadata:s:a:$ffaudioidx",
					 "title=$s",
					"-metadata:s:a:$ffaudioidx",
					 "language=$s");
			} else {
				default_lang:
				push(@cmd_meta, "-metadata:s:a:$ffaudioidx",
					"title=$s") if $s ne "";
			}
			push (@cmd_fa, "-i", $fa->[0]);
			push(@cmd_maps, '-map', $fffileidx++);
			push(@files, $fa->[0]);
			$ffaudioidx++;
		}
		my $ffstidx = 0;
		for my $fs (sort {$a->[0] cmp $b->[0]} @fs) {
			my $extra = $fs->[1];
			$extra =~ s/^\s+//;
			$extra =~ s/\s+$//;
			$extra =~ s/^- //;
			my $s = $extra;
			if (@lang_st) {
				$s = $lang_st[0];
				shift @lang_st if !$one_lang;
			};
			if ($s =~ /^[a-z]{2}$/) {
				push(@{$fn->{st}}, $s);
				push(@ls, $extra);
				if (defined $Languages{$s}) {
					push(@cmd_meta, "-metadata:s:s:$ffstidx",
						 "title=$Languages{$s}{name}",
						"-metadata:s:s:$ffstidx",
						 "language=$Languages{$s}{code3}");
				} else {
					goto default_st;
				}
			} elsif ($s =~ /^[a-z]{3}$/) {
				push(@cmd_meta, "-metadata:s:s:$ffstidx",
					 "title=$s",
					"-metadata:s:s:$ffstidx",
					 "language=$s");
			} else {
				default_st:
				push(@cmd_meta, "-metadata:s:s:$ffstidx",
					 "title=$s") if $s ne "";
			}
			push (@cmd_fs, "-i", $fs->[0]);
			push(@cmd_maps, '-map', $fffileidx++);
			push(@files, $fs->[0]);
			$ffstidx++;
		}
		if (@fc) {
			push (@cmd_fc, "-f", "ffmetadata", "-i", $fc[0][0]);
			push(@cmd_maps, '-map_metadata', $fffileidx++);
			push(@files, $fc[0][0]);
		}
		$fn->joindata();
		my $fv_name = $fn->newname;
		if (defined $fe && $fe eq "mkv")
			{ $fv_name .= ".mkv"; }
		my @cmd = (@cmd_fv, @cmd_fa, @cmd_fs, @cmd_fc, '-c', 'copy', @cmd_maps, @cmd_meta, $fv_name);
		print join(' ', @cmd), "\n";

		if (!$noop && !system{$cmd[0]}(@cmd)) {
			for my $f (@files)
				{ $unlink{$f} = 1; }
			} else {
				for my $f (@files)
					{ $unlink{$f} = $notunlink{$f} = 1; }
		}
	}
	if (!$noop && !$keepfiles) {
		for my $df (keys %unlink) {
			if ($notunlink{$df}) {
				print "keeping $df because of transcoding error\n";
			} else {
				print "rm $df\n";
				unlink($df);
			}
		}
	}
}
