#!/usr/bin/perl
use strict;
use warnings;

use BE::mov::Filename;
#use Data::Dumper;

use IPC::Open3;
use Symbol;

my $rename;
for my $f (@ARGV) {
	if ($f eq "-r") {
		$rename=1; next;
	}
	my $fn = BE::mov::Filename::fn_parse($f, vheight => 1);
	#print Data::Dumper->Dump([$fn], [qw(fn)]);
	my $g = BE::mov::Filename::fn_newname($fn);
	my $d = $fn->{dir};
	print "$g\n";
	if ($rename && $g ne $f) {
		rename("$d/$f", "$d/$g");
		if (-e "$d/$f.sha512") {
			rename("$d/$f.sha512", "$d/$g.sha512");
		}
		my $b = BE::mov::Filename::fn_newbase($fn);
		for my $ext (("txt")) {
			my $f1 = "$d/$fn->{base_orig}.$ext";
			next if !-e $f1;
			rename($f1, "$d/$b.$ext");
		}
	}
}
